# Project
version=1.9.6+kirazium.vtt.1
group=com.dreamdisplays

# Gradle
org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.caching.enabled=true
