minecraft.version=26.1.2
java.version=25
loom.version=1.17.13
moddev.version=2.0.141
fabric.loader.version=0.19.3
quilt.loader.version=0.30.1-beta.2
fabric.api.version=0.155.2+26.1.2
fabric.minecraft.version=26.1.2
fabric.minecraft.dependency=26.1.2
neoforge.version=26.1.2.95
paper.api.version=26.1.2.build.72-stable
paper.minecraft.api=26.1.2
neoforge.loader.range=[26.1.2.0,)
neoforge.minecraft.range=[26.1.2]
