minecraft.version=26.2
java.version=25
loom.version=1.17.13
moddev.version=2.0.141
fabric.loader.version=0.19.3
quilt.loader.version=0.30.0-beta.8
fabric.api.version=0.157.0+26.2
fabric.minecraft.version=26.2
fabric.minecraft.dependency=26.2
neoforge.version=26.2.0.59
paper.api.version=26.2.build.112-stable
paper.minecraft.api=26.2
neoforge.loader.range=[26.2.0.0-beta,)
neoforge.minecraft.range=[26.2]
